sudo: false
language: rust
rust:
  - nightly
env:
  - ARCH=x86_64
  - ARCH=i686
os:
  - linux
cache:
  directories:
    - $HOME/.cargo
script:
  - "cargo build && cargo test"
notifications:
  email: false
