sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.cargo
script:
  - "cargo build && cargo test"
notifications:
  email: false
